export interface RiskReportData {
  scanType: "url" | "email" | "file" | "password";
  result: {
    status: "safe" | "suspicious" | "dangerous";
    score?: number;
    details: string;
    threats?: string[];
  };
  userName?: string;
  timestamp?: Date;
}

const getRiskLevel = (score: number | undefined): string => {
  if (score === undefined) return "UNKNOWN";
  if (score <= 30) return "LOW";
  if (score <= 70) return "MEDIUM";
  return "HIGH";
};

const getRiskIcon = (level: string): string => {
  switch (level) {
    case "HIGH":   return "🔴";
    case "MEDIUM": return "🟠";
    case "LOW":    return "🟢";
    default:       return "⚪";
  }
};

const getStatusEmoji = (status: string): string => {
  switch (status) {
    case "safe":       return "✅ SAFE";
    case "suspicious": return "⚠️ SUSPICIOUS";
    case "dangerous":  return "🚨 DANGEROUS";
    default:           return "❓ UNKNOWN";
  }
};

export const generateRiskReport = (data: RiskReportData): string => {
  const timestamp = data.timestamp
    ? new Date(data.timestamp).toLocaleString()
    : new Date().toLocaleString();

  const riskLevel  = getRiskLevel(data.result.score);
  const riskIcon   = getRiskIcon(riskLevel);
  const statusEmoji = getStatusEmoji(data.result.status);

  const threatsSummary =
    data.result.threats && data.result.threats.length > 0
      ? data.result.threats.map((t) => `  ${getRiskIcon("HIGH")} ${t}`).join("\n")
      : `  ${riskIcon} No specific threats detected`;

  const scanTypeLabel: Record<string, string> = {
    url:      "URL Phishing Detection",
    email:    "Email Breach Check",
    file:     "File Malware Analysis",
    password: "Password Strength Analysis",
  };

  return `
╔════════════════════════════════════════════════════════════╗
║          APGS Risk Report (Security Assessment)            ║
║          Advanced Phishing Guard System  v1.0              ║
╚════════════════════════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 PROJECT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Project:      APGS - Advanced Phishing Guard System
  Version:      1.0.0
  Scan Date:    ${timestamp}
${data.userName ? `  Analyzed By:  ${data.userName}` : ""}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 SCAN OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Scan Type:   ${scanTypeLabel[data.scanType]}
  Purpose:     Comprehensive security analysis powered by VirusTotal
               to identify potential threats in your digital assets.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Risk Level:  ${riskIcon} ${riskLevel}
${data.result.score !== undefined ? `  Risk Score:  ${data.result.score}/100` : ""}
  Status:      ${statusEmoji}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️  THREAT DETECTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${threatsSummary}

  Details:     ${data.result.details}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛡️  RISK LEVEL REFERENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  🔴 HIGH   (Score 71–100) — Critical risk. Immediate action required.
  🟠 MEDIUM (Score 31–70)  — Caution needed. Review before proceeding.
  🟢 LOW    (Score 0–30)   — Appears safe. Standard precautions apply.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📌 FINAL RESULT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  System Status: ${statusEmoji}

${
  data.result.status === "safe"
    ? "  ✅ GREEN LIGHT — Your target appears to be secure and legitimate."
    : data.result.status === "suspicious"
    ? "  ⚠️ CAUTION — Suspicious activity detected. Review and take appropriate action."
    : "  🚨 DANGER — Critical threats identified. Immediate action required."
}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. Review the identified threats carefully
  2. Take corrective action based on the risk level shown above
  3. Keep your security tools and software up to date
  4. Regularly monitor and conduct security assessments
  5. Follow best practices for digital security
${riskLevel === "HIGH" ? "  6. Contact your security team immediately for critical threats\n" : ""}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📞 SUPPORT & CONTACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Email: gyana.tcr20@gmail.com
  Phone: +91 7008584414

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✨ Report Generated by APGS Security Scanner
╔════════════════════════════════════════════════════════════╗
║  This report is confidential and contains sensitive        ║
║  security information. Handle with care.                   ║
╚════════════════════════════════════════════════════════════╝
`;
};

export const downloadReport = (content: string, scanType: string): void => {
  const filename = `APGS_Risk_Report_${scanType}_${new Date().toISOString().split("T")[0]}.txt`;
  const element = document.createElement("a");
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content));
  element.setAttribute("download", filename);
  element.style.display = "none";
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};
